[package]
edition = "2021"
name = "autocorrect-swift"
version = "2.4.3"

[build-dependencies]
swift-bridge-build = "0.1"

[dependencies]
autocorrect = {path = "../autocorrect"}
swift-bridge = "0.1"

[lib]
crate-type = ["staticlib"]
